### ISSUE TITLE
packages.json does not specify a dependency on node-oracledb

### ISSUE THREAD

**Issue by Buto** [OraOpenSource/orawrap#7]
First of all, thank you for orawrap.  We like it a lot.  

Bug: orawrap's packages.json does not specify a dependency on node-oracledb

**Comment by dmcghan** [comment]
@Buto Thanks for you comment. This was omitted intentionally because, unlike most NPM packages, the install of node-oracledb can't be fully automated at this time. One still has to download the instant client, install it, then compile the driver... That's why it was listed as a prerequisite in the documentation. I'll look into making this a bit more obvious. Maybe in the future this can change altogether. Only time will tell.

Thanks again!

**Comment by Buto** [comment]
@dmcghan, Ah I see.  
Got it.

**Comment by dmcghan** [comment]
@Buto I ended up adding oracledb to the package.json for reference purposes. Thanks for your suggestion.
